version: "2.1"
services:
  minecraft:
    image: docker.io/nickmonk/minecraft-server:centos
    container_name: minecraft-server
    hostname: minecraft-server
    volumes:
      - ./minecraft-server:/minecraft-server:z
    ports:
      - 25565:25565/tcp
    restart: unless-stopped
